name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: npm run lint

      - name: Build packages
        run: npm run build

      - name: Publish
        run:
          >
            npx pkg-pr-new publish
            --compact --no-template --pnpm
            './packages/blendtype'
            './packages/nuxt-galaxy'
            './packages/gaas-ui'
