packages:
  - packages/blendtype
  - packages/nuxt-galaxy
  - packages/ui
  - packages/wiki
  - docs
  - playground

catalog:
  '@antfu/eslint-config': ^4.14.1
  '@iconify-json/eos-icons': ^1.2.2
  '@iconify-json/ep': ^1.2.2
  '@iconify-json/lucide': ^1.2.49
  '@iconify-json/majesticons': ^1.2.2
  '@iconify-json/material-symbols': ^1.2.26
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/octicon': ^1.2.6
  '@iconify-json/simple-icons': ^1.2.38
  '@iconify-json/stash': ^1.2.2
  '@iconify-json/streamline': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/tabler': ^1.2.19
  '@iconify-json/vscode-icons': ^1.2.23
  '@release-it/conventional-changelog': ^10.0.1
  '@types/node': ^22.15.31
  '@vitest/coverage-v8': ^3.2.3
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.3.0
  automd: ^0.4.0
  better-sqlite3: ^11.10.0
  bumpp: ^10.1.1
  changelogen: ^0.6.1
  defu: ^6.1.4
  dotenv: ^16.5.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  effect: ^3.16.7
  embla-carousel: ^8.6.0
  eslint: ^9.29.0
  eslint-config-unjs: ^0.4.2
  eslint-plugin-format: ^1.0.1
  fs-extra: ^11.3.0
  h3: ^1.15.3
  happy-dom: ^17.6.3
  jiti: ^2.4.2
  jwt-decode: ^4.0.0
  lint-staged: ^16.1.2
  ofetch: ^1.4.1
  playwright-core: ^1.53.0
  postgres: ^3.4.7
  simple-git-hooks: ^2.13.0
  supabase: ^2.24.3
  tailwindcss: ^4.1.10
  typescript: ^5.8.3
  ufo: ^1.6.1
  unbuild: ^3.5.0
  vitest: ^3.2.3
  vue-tsc: ^2.2.10
  zod: ^3.25.64
  zod-validation-error: ^3.5.0

catalogs:
  nuxt:
    '@nuxt/content': ^3.6.1
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/eslint-config': ^1.4.1
    '@nuxt/image': ^1.10.0
    '@nuxt/kit': ^3.17.5
    '@nuxt/module-builder': ^1.0.1
    '@nuxt/schema': ^3.17.5
    '@nuxt/test-utils': ^3.19.1
    '@nuxt/ui': ^3.1.3
    '@nuxt/ui-pro': ^3.1.3
    '@nuxtjs/supabase': ^1.5.2
    nuxt: ^3.17.5
    nuxt-llms: ^0.1.3
    nuxt-og-image: ^5.1.6
