packages:
  - packages/blendtype
  - packages/nuxt-galaxy
  - packages/ui
  - packages/wiki
  - docs
  - playground

catalog:
  '@antfu/eslint-config': ^5.2.1
  '@iconify-json/eos-icons': ^1.2.4
  '@iconify-json/ep': ^1.2.3
  '@iconify-json/lucide': ^1.2.63
  '@iconify-json/majesticons': ^1.2.4
  '@iconify-json/material-symbols': ^1.2.32
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/octicon': ^1.2.10
  '@iconify-json/simple-icons': ^1.2.48
  '@iconify-json/stash': ^1.2.4
  '@iconify-json/streamline': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.4
  '@iconify-json/tabler': ^1.2.22
  '@iconify-json/vscode-icons': ^1.2.29
  '@release-it/conventional-changelog': ^10.0.1
  '@types/node': ^22.17.2
  '@vitest/coverage-v8': ^3.2.4
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.7.0
  automd: ^0.4.0
  better-sqlite3: ^12.2.0
  bumpp: ^10.2.3
  changelogen: ^0.6.2
  defu: ^6.1.4
  dotenv: ^17.2.1
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  effect: ^3.17.7
  embla-carousel: ^8.6.0
  eslint: ^9.33.0
  eslint-config-unjs: ^0.5.0
  eslint-plugin-format: ^1.0.1
  fs-extra: ^11.3.1
  h3: ^1.15.4
  happy-dom: ^17.6.3
  htl: ^0.3.1
  jiti: ^2.5.1
  jwt-decode: ^4.0.0
  lint-staged: ^16.1.5
  ofetch: ^1.4.1
  playwright-core: ^1.54.2
  postgres: ^3.4.7
  simple-git-hooks: ^2.13.1
  supabase: ^2.34.3
  tailwindcss: ^4.1.12
  typescript: ^5.9.2
  ufo: ^1.6.1
  unbuild: ^3.6.1
  vitest: ^3.2.4
  vue-tsc: ^3.0.5
  zod: ^3.25.76
  zod-validation-error: ^3.5.3

catalogs:
  dataviz:
    '@observablehq/plot': ^0.6.17
    '@uwdata/mosaic-core': ^0.19.1
    '@uwdata/mosaic-sql': ^0.19.0
    '@uwdata/vgplot': ^0.19.1
    d3: ^7.9.0
  nuxt:
    '@nuxt/content': ^3.6.3
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.9.0
    '@nuxt/eslint-config': ^1.9.0
    '@nuxt/image': ^1.11.0
    '@nuxt/kit': ^4.1.1
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.1.1
    '@nuxt/test-utils': ^3.19.2
    '@nuxt/ui': ^3.3.2
    '@nuxt/ui-pro': ^3.3.2
    '@nuxtjs/supabase': ^1.6.0
    nuxt: ^4.1.1
    nuxt-llms: ^0.1.3
    nuxt-og-image: ^5.1.9
