packages:
  - packages/blendtype
  - packages/nuxt-galaxy
  - packages/ui
  - packages/wiki
  - playground

catalog:
  '@antfu/eslint-config': ^4.2.0
  '@iconify-json/eos-icons': ^1.2.2
  '@iconify-json/ep': ^1.2.2
  '@iconify-json/lucide': ^1.2.20
  '@iconify-json/majesticons': ^1.2.2
  '@iconify-json/material-symbols': ^1.2.12
  '@iconify-json/mdi': ^1.2.2
  '@iconify-json/octicon': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.22
  '@iconify-json/stash': ^1.2.2
  '@iconify-json/streamline': ^1.2.2
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/tabler': ^1.2.13
  '@release-it/conventional-changelog': ^10.0.0
  '@types/node': ^22.10.2
  '@vitest/coverage-v8': ^3.0.7
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.1.0
  automd: ^0.4.0
  bumpp: ^10.0.2
  changelogen: ^0.6.0
  defu: ^6.1.4
  dotenv: ^16.4.7
  drizzle-kit: ^0.31.0
  drizzle-orm: ^0.43.1
  effect: ^3.14.1
  eslint: ^9.21.0
  eslint-config-unjs: ^0.4.2
  eslint-plugin-format: ^1.0.1
  fs-extra: ^11.2.0
  h3: ^1.13.0
  happy-dom: ^17.1.8
  jiti: ^2.4.2
  jwt-decode: ^4.0.0
  lint-staged: ^15.3.0
  ofetch: ^1.4.1
  playwright-core: ^1.50.0
  postgres: ^3.4.5
  simple-git-hooks: ^2.11.1
  supabase: ^2.15.8
  tailwindcss: ^4.0.10
  typescript: ^5.8.3
  ufo: ^1.5.4
  unbuild: ^3.5.0
  vitest: ^3.0.4
  vue-tsc: ^2.2.0
  zod: ^3.24.1
  zod-validation-error: ^3.4.0

catalogs:
  nuxt:
    '@nuxt/content': ^3.5.1
    '@nuxt/devtools': ^2.4.0
    '@nuxt/eslint-config': ^1.1.0
    '@nuxt/kit': ^3.17.0
    '@nuxt/module-builder': ^1.0.1
    '@nuxt/schema': ^3.17.0
    '@nuxt/test-utils': ^3.17.0
    '@nuxt/ui': ^3.1.1
    '@nuxt/ui-pro': ^3.1.1
    '@nuxtjs/supabase': ^1.5.0
    nuxt: ^3.17.0
