shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - nuxt-component-meta@0.17.1
  - chokidar@4.0.3
  - undici-types@6.21.0
  - undici@6.22.0
  - semver@6.3.1
  - '@nuxtjs/supabase@2.0.4'
  - rxjs@7.8.2
  - nuxt-component-meta@0.17.2
packages:
  - packages/blendtype
  - packages/nuxt-galaxy
  - packages/ui
  - packages/wiki
  - docs
  - playground

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@dotenvx/dotenvx': ^1.52.0
  '@iconify-json/eos-icons': ^1.2.4
  '@iconify-json/ep': ^1.2.4
  '@iconify-json/lucide': ^1.2.95
  '@iconify-json/majesticons': ^1.2.4
  '@iconify-json/material-symbols': ^1.2.59
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/octicon': ^1.2.21
  '@iconify-json/simple-icons': ^1.2.71
  '@iconify-json/solar': ^1.2.5
  '@iconify-json/stash': ^1.2.4
  '@iconify-json/streamline': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.4
  '@iconify-json/tabler': ^1.2.28
  '@iconify-json/vscode-icons': ^1.2.44
  '@release-it/conventional-changelog': ^10.0.5
  '@types/node': ^24.11.0
  '@unocss/eslint-plugin': ^66.6.3
  '@vitest/coverage-v8': ^3.2.4
  '@vue/compiler-core': ^3.5.29
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^14.2.1
  apache-arrow: ^21.1.0
  automd: ^0.4.3
  better-sqlite3: ^12.6.2
  bumpp: ^10.4.1
  changelogen: ^0.6.2
  citty: ^0.2.1
  defu: ^6.1.4
  dotenv: ^17.3.1
  drizzle-kit: ^1.0.0-beta.9-e89174b
  drizzle-orm: ^1.0.0-beta.9-e89174b
  effect: ^3.19.19
  embla-carousel: ^8.6.0
  esbuild: ^0.27.3
  eslint: ^9.39.3
  eslint-config-unjs: ^0.6.2
  eslint-plugin-format: ^1.5.0
  fs-extra: ^11.3.3
  h3: ^1.15.5
  happy-dom: ^20.7.0
  htl: ^0.3.1
  jiti: ^2.6.1
  jwt-decode: ^4.0.0
  lint-staged: ^16.3.1
  meilisearch: ^0.55.0
  ofetch: ^1.5.1
  playwright-core: ^1.58.2
  postgres: ^3.4.8
  simple-git-hooks: ^2.13.1
  supabase: ^2.76.15
  typescript: ^5.9.3
  ufo: ^1.6.3
  unbuild: ^3.6.1
  uuid: ^13.0.0
  vitest: ^3.2.4
  vue: latest
  vue-router: latest
  vue-tsc: ^3.2.5
  zod: ^4.3.6
  zod-validation-error: ^5.0.0

catalogs:
  dataviz:
    '@observablehq/plot': ^0.6.17
    '@types/d3': ^7.4.3
    '@uwdata/mosaic-core': ^0.21.1
    '@uwdata/mosaic-sql': ^0.21.1
    '@uwdata/vgplot': ^0.21.1
    d3: ^7.9.0
    d3-dsv: ^3.0.1
  nuxt:
    '@nuxt/content': ^3.12.0
    '@nuxt/devtools': ^2.7.0
    '@nuxt/eslint': ^1.15.2
    '@nuxt/image': ^1.11.0
    '@nuxt/kit': ^4.3.0
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.3.0
    '@nuxt/test-utils': ^3.23.0
    '@nuxt/ui': ^4.5.0
    '@nuxtjs/supabase': ^2.0.4
    '@pinia/colada-nuxt': ^0.3.2
    '@pinia/nuxt': ^0.11.3
    nuxt: ^4.3.0
    nuxt-llms: ^0.2.0
    nuxt-og-image: ^5.1.13
    nuxt-studio: ^1.4.0
  vue:
    '@pinia/colada': ^0.21.6
    '@pinia/colada-devtools': ^0.4.4
    pinia: ^3.0.4

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - supabase
