packages:
  - packages/*
  - playground
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@iconify-json/ep': ^1.2.2
  '@iconify-json/lucide': ^1.2.20
  '@iconify-json/material-symbols': ^1.2.12
  '@iconify-json/mdi': ^1.2.2
  '@iconify-json/streamline': ^1.2.2
  '@iconify-json/tabler': ^1.2.13
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/majesticons': ^1.2.2
  '@iconify-json/stash': ^1.2.2
  '@nuxt/devtools': ^1.7.0
  '@nuxt/eslint-config': ^0.7.4
  '@nuxt/kit': ^3.15.0
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.15.0
  '@nuxt/test-utils': ^3.15.1
  '@nuxt/ui-pro': 3.0.0-alpha.11
  '@nuxt/ui': 3.0.0-alpha.11
  '@nuxtjs/supabase': ^1.4.5
  '@release-it/conventional-changelog': ^9.0.4
  '@tailwindcss/typography': ^0.5.15
  '@types/node': ^22.10.2
  '@vitest/coverage-v8': ^2.1.8
  '@vueuse/core': ^12.3.0
  automd: ^0.3.12
  bumpp: ^9.9.2
  changelogen: ^0.5.7
  defu: ^6.1.4
  dotenv: ^16.4.7
  drizzle-kit: ^0.30.1
  drizzle-orm: ^0.38.3
  eslint: ^9.17.0
  eslint-config-unjs: ^0.4.2
  eslint-plugin-format: ^0.1.3
  fs-extra: ^11.2.0
  h3: ^1.13.0
  jiti: ^2.4.2
  jwt-decode: ^4.0.0
  lint-staged: ^15.3.0
  nuxt: ^3.15.2
  ofetch: 1.4.1
  postgres: ^3.4.5
  simple-git-hooks: ^2.11.1
  ufo: ^1.5.4
  unbuild: ^3.0.1
  vitest: ^2.1.8
  vue-tsc: ^2.2.0
  zod: ^3.24.1
  zod-validation-error: ^3.4.0
