packages:
  - packages/blendtype
  - packages/nuxt-galaxy
  - packages/ui
  - packages/wiki
  - docs
  - playground

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@iconify-json/eos-icons': ^1.2.4
  '@iconify-json/ep': ^1.2.3
  '@iconify-json/lucide': ^1.2.71
  '@iconify-json/majesticons': ^1.2.4
  '@iconify-json/material-symbols': ^1.2.44
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/octicon': ^1.2.16
  '@iconify-json/simple-icons': ^1.2.56
  '@iconify-json/stash': ^1.2.4
  '@iconify-json/streamline': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.4
  '@iconify-json/tabler': ^1.2.23
  '@iconify-json/vscode-icons': ^1.2.33
  '@release-it/conventional-changelog': ^10.0.1
  '@types/node': ^22.18.13
  '@vitest/coverage-v8': ^3.2.4
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.9.0
  automd: ^0.4.2
  better-sqlite3: ^12.4.1
  bumpp: ^10.3.1
  changelogen: ^0.6.2
  defu: ^6.1.4
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.6
  drizzle-orm: ^0.44.7
  effect: ^3.18.4
  embla-carousel: ^8.6.0
  eslint: ^9.39.0
  eslint-config-unjs: ^0.5.0
  eslint-plugin-format: ^1.0.2
  fs-extra: ^11.3.2
  h3: ^1.15.4
  happy-dom: ^17.6.3
  htl: ^0.3.1
  jiti: ^2.6.1
  jwt-decode: ^4.0.0
  lint-staged: ^16.2.6
  ofetch: ^1.5.1
  playwright-core: ^1.56.1
  postgres: ^3.4.7
  simple-git-hooks: ^2.13.1
  supabase: ^2.54.11
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  ufo: ^1.6.1
  unbuild: ^3.6.1
  vitest: ^3.2.4
  vue-tsc: ^3.1.2
  zod: ^3.25.76
  zod-validation-error: ^3.5.3

catalogs:
  dataviz:
    '@observablehq/plot': ^0.6.17
    '@uwdata/mosaic-core': ^0.21.1
    '@uwdata/mosaic-sql': ^0.21.1
    '@uwdata/vgplot': ^0.21.1
    d3: ^7.9.0
    d3-dsv: ^3.0.1
  nuxt:
    '@nuxt/content': ^3.8.0
    '@nuxt/devtools': ^2.7.0
    '@nuxt/eslint': ^1.10.0
    '@nuxt/eslint-config': ^1.10.0
    '@nuxt/image': ^1.11.0
    '@nuxt/kit': ^4.1.2
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.1.2
    '@nuxt/test-utils': ^3.20.1
    '@nuxt/ui': ^4.1.0
    '@nuxtjs/supabase': ^1.6.2
    nuxt: ^4.1.2
    nuxt-llms: ^0.1.3
    nuxt-og-image: ^5.1.12

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - supabase
