import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '../../../types/database'

import { defineQueryOptions } from '@pinia/colada'

export const DISK_USAGE_QUERY_KEYS = {
  root: ['disk-usage'] as const,
  byUser: (userId: string) => [...DISK_USAGE_QUERY_KEYS.root, 'user', userId] as const,
}

async function supabaseDiskUsageQuery(supabase: SupabaseClient<Database>, userId: string) {
  const [uploadedResult, datasetResult] = await Promise.all([
    // this correspond to all the files uploaded
    supabase
      .schema('galaxy')
      .from('uploaded_datasets_with_storage_path')
      .select('metadata')
      .eq('owner_id', userId),
    // this correspond to all the files generated by galaxy (e.g. outputs of analyses)
    // do not include the "datasets" because it include input datasets that are already counted in the "uploaded_datasets_with_storage_path" table
    supabase
      .schema('galaxy')
      .from('analysis_outputs_with_storage_path')
      .select('metadata')
      .eq('owner_id', userId),
  ])

  if (uploadedResult.error) {
    throw new Error(`Failed to get uploaded datasets: ${uploadedResult.error.message}`)
  }
  if (datasetResult.error) {
    throw new Error(`Failed to get datasets: ${datasetResult.error.message}`)
  }

  const sumMetadataSize = (rows: unknown[]) => rows.reduce((acc: number, row) => {
    const metadata = (row as { metadata?: { size?: number } }).metadata
    return acc + (metadata?.size ?? 0)
  }, 0)

  return sumMetadataSize(uploadedResult.data ?? []) + sumMetadataSize(datasetResult.data ?? [])
}

export const diskUsageByUserQuery = defineQueryOptions(
  ({ supabase, userId }: { supabase: SupabaseClient<Database>, userId: string }) => ({
    key: DISK_USAGE_QUERY_KEYS.byUser(userId),
    query: () => supabaseDiskUsageQuery(supabase, userId),
  }),
)
