name: ci

on:
  push:
    branches:
      - main
      - use-effect
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: npm run lint

      - name: Build packages
        run: npm run build
        env:
          NUXT_UI_PRO_LICENSE: ${{secrets.NUXT_UI_PRO_LICENSE}}
      - name: Publish
        run:
          >
            npx pkg-pr-new publish
            --no-template --pnpm
            './packages/blendtype'
            './packages/nuxt-galaxy'
            './packages/ui'
            './packages/wiki'
